name: docker-cache

on:
  push:

jobs:
  build:
    runs-on: shubhi-vps
    container:
      image: gcr.io/google-containers/addon-builder
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

          
