name: docker-cache

on:
  push:

jobs:
  build:
    runs-on: test-label1
    container:
      image: gcr.io/google-containers/alpine-iptables-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

          
