name: docker-cache

on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker Caching
        uses: actions/cache@v2
        id: docker-cache
        with:
          path: /var/lib/docker/
          key: ${{ runner.os }}

      - name: Docker image pull
        run: |
          time docker pull shubhindia/wso2km:5.7