name: docker-cache

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v2
        with:
          path: api
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles', '**/gemfile') }}
