name: docker-cache

on:
  push:
    paths-ignore:
      - 'ap/**'

jobs:
  build:
    runs-on: docker-self-hosted
    strategy:
      max-parallel: 1
      matrix:
        job: [0,1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker Caching
        uses: actions/cache@v2
        id: docker-cache
        with:
          path: /var/lib/docker/
          key: ${{ runner.os }}-1

      - name: Docker image pull
        run: |
          time docker pull shubhindia/wso2km:latest

      - name: Test exit
        run: echo ${{ strategy.job-total }}
