name: docker-cache

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.6.9-stretch
      volumes:
        - /home/runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: List files
        run: ls -la
