name: docker-cache

on:
  push:
    paths-ignore:
      - 'ap/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        job: [0,1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker Caching
        uses: actions/cache@v2
        id: docker-cache
        with:
          path: /var/lib/docker/
          key: ${{ runner.os }}-1

      - name: Docker image pull
        run: |
          time docker pull shubhindia/wso2km:latest

      - name: Test exit
        run: |
          if [[ ${{ matrix.job }} == '0' ]]
          then
            exit 1
          else
            echo ${{ matrix.job }}
          fi

      - name: Some maths here
        run: |
          divnum=$( expr 100 / ${{ strategy.job-total }})
          echo $divnum

  Coveralls:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Just placebo
        run: echo "Coveralls""